# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5e76e34dc586f37140d3e6ba195429d251ac85b80958f2ec921d1a94946362c23281c95cab42d96aa28aa78fdc1adc9ccb8d2fcb645ca8910608d8388d5ff69

test:
  secret_key_base: a514f41374b82ecf6981f64a430906b9bac4a50192812dd069bbec5d46ce8fa687060414af83c83e046b85915e47d2239cc6875a5174b8892d4c509269c8be1f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
